mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^track/', include('track.urls', namespace="track")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/track/urls.py
from django.conf.urls import patterns, url, include
from track import views
from track.views import RecordUpdate, RecordCreate, AthleteCreate

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^athletes/', views.AthleteList, name='athlete_list'),
    url(r'^(?P<athlete_id>\d+)/', views.AthleteProfile, name='athlete_profile'),
    url(r'^edit/(?P<pk>\d+)/', RecordUpdate.as_view(), name='record_update_form'),
    url(r'^add_record/(?P<pk>\d+)/', RecordCreate.as_view(), name='record_create_form'),
    url(r'^add_athlete/', AthleteCreate.as_view(), name='athlete_create_form'),
    url(r'^events/(?P<event_id>\d+)/', views.EventProfile, name='event_profile'),
)

mysite/track/models.py
from django.db import models
import PIL

class Event(models.Model):
	def __str__(self):
		return (self.gender + ' ' + self.event_name)
	
	BOYS = 'B'
	GIRLS = 'G'
	CHOICES = (
		(BOYS, 'Boys'),
		(GIRLS, 'Girls'),
	)
	
	gender = models.CharField(max_length=1, choices=CHOICES, null=False)
	event_name = models.CharField(max_length=20, null=False)
	
	class Meta:
		unique_together = ('event_name', 'gender')
	
class Athlete(models.Model):
	def __str__(self):
		return (self.first_name + ' ' + self.last_name)

	FRESHMAN = 'FR'
	SOPHOMORE = 'SO'
	JUNIOR = 'JR'
	SENIOR = 'SR'
	CHOICES = (
		(FRESHMAN, 'Freshman'),
		(SOPHOMORE, 'Sophomore'),
		(JUNIOR, 'Junior'),
		(SENIOR, 'Senior'),
	)
	
	BOY = 'B'
	GIRL = 'G'
	OPTIONS = (
		(BOY, 'Boy'),
		(GIRL, 'Girl'),
	)
	
	gender = models.CharField(max_length=1, choices=OPTIONS, null=False)
	year = models.CharField(max_length=2, choices=CHOICES, default=FRESHMAN)
	first_name = models.CharField(max_length=20, null=False)
	last_name = models.CharField(max_length=20, null=False)
	
	class Meta:
		unique_together = ('first_name', 'last_name')
		
class Record(models.Model):
	event_name = models.ForeignKey(Event, default=1)
	athlete = models.ForeignKey(Athlete, default=1)
	time_dist = models.DecimalField('Time/Distance', decimal_places=2, max_digits=5)
	date = models.DateField()
	
	class Meta:
		unique_together = ('event_name', 'athlete')

mysite/track/views.py
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from track.models import Athlete, Event, Record

def index(request):
	events = []
	event_names = Event.objects.values_list('event_name', flat=True).distinct()
	for event in event_names:
		event_number = Event.objects.filter(event_name=event).values_list('id', flat=True)[0]
		events += Event.objects.filter(pk=event_number)
		print BASE_DIR
	return render(request, 'track/index.html', { 'events' : events })
 
def AthleteList(request):
	if 'search_term' in request.GET:
		results = Athlete.objects.filter(
				Q(last_name__icontains=request.GET['search_term']) |
				Q(first_name__icontains=request.GET['search_term']))
		
		if len(results) == 1:
			url = reverse('track:athlete_profile', args=(results[0].id,))
			return redirect(url)
		else:
			return render(request, 'track/athlete_list.html', { 'athletes' : results })
	
	else:
		all = Athlete.objects.all()
		return render(request, 'track/athlete_list.html', { 'athletes' : all })

def AthleteProfile(request, athlete_id):
	records = Record.objects.filter(athlete=athlete_id)
	athlete = Athlete.objects.filter(pk=athlete_id)
	return render(request, 'track/athlete_profile.html', { 'records' : records, 'athlete' : athlete })


def EventProfile(request, event_id):
	event_profiles = []
	
	event_name = (Event.objects.get(pk=event_id)).event_name
	events = Event.objects.filter(event_name=event_name)
	
	for event in events:
		records = Record.objects.filter(event_name=event.id).order_by('time_dist')
		event_profile = { 'event' : event, 'records' : records }
		event_profiles.append(event_profile)
	return render(request, 'track/event_profile.html', { 'event_profiles' : event_profiles })

class RecordUpdate(UpdateView):
	model = Record
	template_name_suffix = '_update_form'
	fields = [ 'event_name', 'time_dist', 'date' ]

	def get_success_url(self):
		return reverse('track:athlete_profile', kwargs={ 'athlete_id': self.get_object().athlete.id })

class RecordCreate(CreateView):
	model = Record
	template_name_suffix = '_create_form'
	fields = ['athlete', 'event_name', 'time_dist', 'date' ]

	def get_initial(self):
		athlete = Athlete.objects.get(id=self.kwargs.get('pk'))
		initial = super(RecordCreate, self).get_initial()
		initial = initial.copy()
		initial['athlete'] = athlete
		return initial
	
	def get_success_url(self):
		return reverse('track:athlete_profile', kwargs={ 'athlete_id': self.get_object().id })
		
class AthleteCreate(CreateView):
	model = Athlete
	template_name_suffix = '_create_form'
	
	def get_success_url(self):
		return reverse('track:athlete_list')

mysite/track/templates/track/athlete_create_form.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>

  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>

      <form role="form" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
      </form>

    </div>
  </body>
</html>

mysite/track/templates/track/athlete_list.html
{% load staticfiles %}
<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'track/profile.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>
  
  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>
      
      <h2 class="text-center">Roster</h2>

      <form role="form" action="/track/athletes/" method="GET">
        <div class="form-group">
          <input type="text" class="form-control" name="search_term" 
          placeholder="&#xf002;">
        </div>
      </form>
      
      <p class="text-center">
        <a id="add" href="{% url 'track:athlete_create_form' %}">
          <i class="fa fa-plus fa-fw"></i>Athlete
        </a>
      </p>
      
      <hr>
        
      <div class="container-fluid">
        {% if athletes %}
          {% for a in athletes %}
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li>
                  <h5><small>{{ a.year }} {{ a.gender }}</small>
                  <a href="{% url 'track:athlete_profile' a.id %}"> - {{a.first_name}} {{a.last_name}}</a></h5>
                </li>
              </ul>
            </div>
          {% endfor %}
        {% else %}
          <p class="text-center"> No Results </p>
        {% endif %}
      </div>
    
    </div>
  </body>
</html>
    
  

mysite/track/templates/track/athlete_profile.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'track/profile.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>
  
  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>
      
    <table class="table">
      <caption>
        {% for a in athlete %}
          <h2 class="text-center">{{ a.first_name }} {{ a.last_name }}</h2>
        {% endfor %}
      </caption>
      <tr>
        <th class="text-center">Event</th>
        <th class="text-center">Time/Distance</th>
        <th class="text-center">Date</th>
        <th class="text-center">Update</th>
      </tr>
      {% for record in records %}
        <tr>
          <td class="text-center"><a href="{% url 'track:event_profile' record.event_name.id %}">{{ record.event_name }}</a></td>
          <td class="text-center">{{ record.time_dist }}</td>
          <td class="text-center">{{ record.date }}</td>
          <td class="text-center">
            <a href="{% url 'track:record_update_form' pk=record.id %}"><i class="fa fa-edit fa-fw"></i></a>
          </td>
        </tr>
      {% endfor %}
    </table>
    
    <hr>

    <p class="text-center">
      <a id="add" href="{% url 'track:athlete_create_form' %}">
        <i class="fa fa-plus fa-fw"></i>Personal Record
      </a>
    </p>
    
    </div>
  </body>
</html>
 

mysite/track/templates/track/event_profile.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>

  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>

      {% for event_profile in event_profiles %}
        <table class="table">
        <caption>
          <h2>{{ event_profile.event.get_gender_display }} {{event_profile.event.event_name }}</h2>
        </caption>
        <tr>
          <th class="text-center">Athlete</th>
          <th class="text-center">Time/Distance</th>
          <th class="text-center">Date</th>
        {% for record in event_profile.records %}
          <tr>
          <td class="text-center">
            <a href="{% url 'track:athlete_profile' record.athlete.id %}">{{ record.athlete }}</a></td>
          <td class="text-center">{{ record.time_dist }}</td>
          <td class="text-center">{{ record.date }}</td>
        {% endfor %}
        </table>
        <hr>
      {% endfor %}
    </div>
  </body>
</html>

mysite/track/templates/track/index.html
{% load staticfiles %}
<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>
  
  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>
    
      <h2 class="text-center">Athletes</h2>
    
      <form role="form" action="/track/athletes/" method="GET">
        <div class="form-group">
          <input type="text" class="form-control" name="search_term" 
          placeholder="&#xf002;">
        </div>
      </form>
    
      <hr>

      <h2 class="text-center">Events</h2>
  
      <div class="container-fluid">
        {% if events %}
          {% for e in events %}
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li class="centered"><a href="{% url 'track:event_profile' e.id %}">{{e.event_name}}</a></li>
              </ul>
            </div>
          {% endfor %}
        {% else %}
          <p> Error Loading Events</p>
        {% endif %}
      </div>
      
      <hr>
      
    </div>
  </body>
</html>

mysite/track/templates/track/record_create_form.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>

  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>

      <form role="form" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
      </form>

    </div>
  </body>
</html>

mysite/track/templates/track/record_update_form.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <title> RHS Track and Field </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'track/base.css' %}" />
      <link rel='stylesheet' type='text/css'
      href='http://fonts.googleapis.com/css?family=Libre+Baskerville' >
    </head>

  <body>
    <div class="container">
  	  <h1>Roseburg Track and Field</h1>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'track:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li> 
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-user fa-fw"></i>Admin</a></li>
              <li><a href="{% url 'track:athlete_list' %}"><i class="fa fa-trophy fa-fw"></i>Roster</a></li> 
            </ul>
          </div>
        </div>
      </nav>

      <form role="form" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
      </form>

    </div>
  </body>
</html>